# Generated by Django 5.2.6 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, help_text='Emergency contact email for notifications', max_length=254),
        ),
    ]
