# Generated by Django 5.2.6 on 2025-09-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_counselor_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CounselorProfile",
        ),
    ]
