# Generated by Django 5.2.6 on 2025-09-25 04:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_delete_counselorprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="call_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, help_text="Actual call duration", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="call_provider",
            field=models.CharField(
                blank=True,
                help_text="Calling service provider (Twilio, Agora, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="call_quality_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Technical call quality rating",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="call_recording_url",
            field=models.URLField(
                blank=True, help_text="Call recording link (if enabled)"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="call_session_id",
            field=models.CharField(
                blank=True, help_text="Third-party call API session ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="counselor_phone",
            field=models.CharField(
                blank=True,
                help_text="Counselor's phone number for calls",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="counselor_preference_type",
            field=models.CharField(
                choices=[
                    ("no_preference", "No Preference"),
                    ("specific_counselor", "Specific Counselor Requested"),
                    ("gender_preference", "Gender Preference"),
                    ("specialty_preference", "Specialty Preference"),
                ],
                default="no_preference",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="preference_reason",
            field=models.TextField(
                blank=True, help_text="Reason for counselor preference"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="preferred_counselor",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's preferred counselor",
                limit_choices_to={"role": "counselor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="student_phone",
            field=models.CharField(
                blank=True, help_text="Student's phone number for calls", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In Person"),
                    ("video_call", "Video Call"),
                    ("phone_call", "Phone Call"),
                    ("chat_only", "Chat Only"),
                    ("voice_call", "Voice Call"),
                ],
                default="video_call",
                max_length=20,
            ),
        ),
    ]
